apiVersion: v1
kind: Pod
metadata:
  name: cndp-0-0
  annotations:
    k8s.v1.cni.cncf.io/networks: afxdp-network
spec:
  containers:
    - name: cndp-0
      command: ["tail", "-f", "/dev/null"]
      image:  quay.io/mtahhan/cndp-map-pinning:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        capabilities:
          add:
            - NET_RAW
            - IPC_LOCK
            #- BPF                                 # Only needed if Kernel version <= 5.18
      resources:
        requests:
          afxdp/myPool: '1'
        limits:
          afxdp/myPool: '1'
