name: Build AF_XDP Device Plugin Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths: [.github/workflows/build-image.yml]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - registry: quay.io
            organization: afxdp-plugins-for-kubernetes
            image: afxdp-device-plugin
            dockerfile: ./images/amd64.dockerfile
            context: .
            tags: 'latest'

    steps:
     - uses: actions/checkout@v4

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
    
     - name: Login to quay.io
       uses: docker/login-action@v3
       with:
          registry: ${{matrix.registry}}/${{matrix.organization}}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
          
     - name: Build and push image
       uses: docker/build-push-action@v5
       with:
          push: true
          tags: ${{matrix.registry}}/${{matrix.organization}}/${{matrix.image}}:${{matrix.tags}}
          labels: 'latest'
          file: ${{ matrix.dockerfile }}
          build-args: ${{ matrix.build_args }}
          context: ${{ matrix.context }}
